
const labels = {
  add: "Adaugă",
  tab1: "Listă Materiale", 
  stare: "Stare",
  tip: "Tip",
  confirm: "Confirmă",
  detaliiMaterial: "Detalii Material",
  descriere: "Descriere",
  nume: "Nume",
  createdAt: "Creat la",
  updatedAt: "Modificat la",
  componente: "Componente",
  filtruStare: "Filtru Stare",
  filtruData: "Filtru Dată",
  demo: "DEMO",
  scan: "Scanează QR",
  adauga: "Adaugă Material",
  detalii: "Detalii", 
  sterge: "Șterge Material",
  adaugaComponenta: "Adaugă Componentă (QR)",
  exportEticheta: "Exportă Etichetă",
  billOfMaterials: "Listă Componente (BOM)",
  materiiPrime: "Materii Prime",
  materialePrelucrate: "Materiale Prelucrate",
  niciunMaterialGasit: "Niciun material găsit.",
  nicioComponentaAdaugata: "Nicio componentă adăugată.",
  nicioMateriePrimaGasita: "Nicio materie primă găsită.",
  niciunMaterialPrelucratGasit: "Niciun material prelucrat găsit.",
  materialNegasit: "Materialul nu a fost găsit.",
  salveazaSiPleaca: "Salvează și Pleacă",
  parasesteFaraSalvare: "Părăsește fără Salvare",
  ramaiPePagina: "Rămâi pe Pagină",
  modificariNesalvate: "Modificări Nesalvate",
  modificariNesalvateInfo: "Ai modificări nesalvate. Ce vrei să faci?",
  confirmareStergere: "Confirmare Ștergere",
  confirmareStergereInfo: "Sigur vrei să ștergi acest material?",
  confirmareStergereFurnizorInfo: "Sigur vrei să ștergi acest furnizor? Această acțiune nu poate fi anulată.",
  anuleaza: "Anulează",
  daSterge: "Da, Șterge",
  exportPDF: "Exportă PDF Raport",
  descarcaQR: "Descarcă Etichetă QR",
  etichetaQR: "Etichetă QR",
  inchide: "Închide",
  eroareScanare: "Eroare la scanare.",
  qrInvalidMaterial: "QR-ul nu conține un material valid.",
  componentaAdaugata: "Componentă adăugată cu succes!",
  materialSalvat: "Material salvat cu succes!",
  permisiuneCameraRefuzata: "Permisiune cameră refuzată",
  permisiuneCameraInfo: "Te rugăm acordă permisiunea pentru cameră pentru a folosi scanerul de coduri de bare.",
  materialInexistent: "Material inexistent",
  materialInexistentInfo: "Materialul scanat nu există în aplicație: ",
  qrInvalidGeneral: "Codul QR scanat nu conține date valide de material.",
  pdfSalvatDocuments: "PDF salvat în folderul Documents!",
  eroareSalvarePDF: "Eroare la salvarea PDF-ului.",
  qrSalvat: "Imaginea etichetei QR a fost salvată!",
  deLa: "De la",
  panaLa: "Până la",
  filtre: "Filtre",
  toate: "Toate",
  selecteazaStarea: "Selectează starea",
  selecteazaTipul: "Selectează tipul",
  furnizor: "Furnizor",
  gestiuneFurnizori: "Gestiune Furnizori",
  adaugaFurnizor: "Adaugă Furnizor",
  editeazaFurnizor: "Editează Furnizor",
  detaliiFurnizor: "Detalii Furnizor",
  numeFurnizor: "Nume Furnizor (Entitate Legală)",
  persoanaContact: "Persoană Contact",
  email: "Email",
  telefon: "Telefon",
  adresa: "Adresă (Entitate Legală)",
  niciunFurnizorGasit: "Niciun furnizor găsit.",
  selecteazaFurnizor: "Selectează un furnizor",
  furnizorSalvat: "Furnizor salvat cu succes!",
  campObligatoriu: "Acest câmp este obligatoriu.",
  stergeFurnizor: "Șterge Furnizor",

  // IKEA Supplier Fields
  ikeaSupplierId: "ID Furnizor IKEA",
  complianceOfficerInfo: "Info Ofițer Conformitate & Pers. Contact IKEA",
  subSupplierInfo: "Detalii Sub-furnizori/Subcontractori",
  traceabilitySystemDescription: "Descriere Sistem Trasabilitate Furnizor",
  supplyChainFlowChartData: "Diagramă Lanț Aprovizionare (Date/Link)",
  latestThirdPartyAuditReports: "Ultimele Rapoarte Audit Terți (FSC, IKEA)",
  correctiveActionPlans: "Planuri Acțiuni Corective (CAPs)",
  ikeaOwnAuditResults: "Rezultate Audit Propriu IKEA",
  legalComplianceDeclarations: "Declarații Conformitate Legală (EUTR/DDS)",

  // IKEA Material Fields
  detaliiOrigineLemnIKEA: "Detalii Origine Lemn (IKEA)",
  countryOfHarvest: "Țara Recoltării",
  regionAndForestName: "Regiune și Nume Pădure",
  gpsCoordinatesOrFMU: "Coordonate GPS / FMU",
  forestOwnership: "Statut Proprietate Pădure",
  forestType: "Tip Pădure",
  harvestDateOrPeriod: "Data/Perioada Recoltării",
  treeSpeciesScientific: "Specie Arbore (Științific)",
  treeSpeciesCommon: "Specie Arbore (Comun)",
  estimatedVolumePerSpeciesRWE: "Volum Estimat/Specie (RWE m³)",
  
  documentatieLegalaIKEA: "Documentație Legală (IKEA)",
  loggingPermitOrLicense: "Permis Exploatare / Licență Recoltare",
  landTenureAndUseRights: "Drepturi Proprietate Funciară și Folosință Pădure",
  chainOfCustodyRecords: "Înregistrări Lanț Custodie (CoC)",
  transportPermits: "Permise Transport (dacă aplicabil)",
  dueDiligenceRecordsSubSuppliers: "Înregistrări Due Diligence Sub-furnizori",

  certificareIKEA: "Informații Certificare (IKEA)",
  forestCertificationScheme: "Schemă Certificare Pădure (ex: FSC, PEFC)",
  certificationNumber: "Număr Certificat",
  certificationScope: "Domeniu Certificare",
  certificationValidityPeriod: "Perioadă Valabilitate Certificat",
  productGroupAndClaimType: "Grup Produs și Tip Revendicare (ex: FSC 100%)",
  cocCertificateCopies: "Copii Certificate Lanț Custodie (CoC)",
  certificationAuditSummaries: "Sumare Audit Certificare (opțional)",

  trasabilitateMaterialIKEA: "Trasabilitate Material (IKEA)",
  inputOutputReconciliation: "Reconciliere Intrare/Ieșire (Lemn vs. Produse)",
  batchLevelTrackingInfo: "Info Urmărire Nivel Lot Material",
  rawMaterialLedgerInfo: "Registru Materie Primă (inclusiv intrări sub-furnizori)",

  metriciSustenabilitateIKEA: "Metrici Sustenabilitate (IKEA)",
  recycledContentPercentage: "Procent Conținut Reciclat (%)",
  carbonFootprintData: "Date Amprentă Carbon (opțional)",
  resourceEfficiencyOrWasteData: "Eficiență Resurse / Date Deșeuri (dacă necesar)",
  forestManagementPlanDetails: "Detalii Plan Management Pădure (pt. Lemn Controlat FSC / necertificat)",

  infoLivrareProductieIKEA: "Info Livrare & Producție (IKEA)",
  finalProcessingLocation: "Locație Procesare Finală (țară, nume unitate)",
  ikeaProductType: "Tip Produs IKEA (ex: placaj, PAL, lemn masiv)",
  ikeaProductNamesOrArticles: "Nume/Articole Produs IKEA care utilizează lemnul",
  packingListTraceableToRawMaterial: "Packing List Trasabil la Materia Primă (Link/Referință)",

  instrumenteVerificareProvenientaIKEA: "Instrumente Verificare Proveniență (IKEA)",
  worldForestIDParticipation: "Participare World Forest ID (amprentare lemn)",
  forensicTestData: "Date Teste Forensice (izotop/fibră/chimic)",
  gpsOrBlockchainTraceabilityTools: "Instrumente Trasabilitate GPS/Blockchain (dacă se utilizează)",

  // Lumber Mill Specific Labels
  detaliiSpecificeLemnMoara: "Detalii Specifice Lemn (Moară)",
  logDiameter: "Diametru Buștean (ex: 30-50 cm)",
  logLength: "Lungime Buștean (ex: 4m, 6m)",
  logGrade: "Clasă Calitate Buștean (ex: A, B)",
  estimatedWeightKg: "Greutate Estimată Buștean (kg)",
  defectDescription: "Descriere Defecte Buștean",
  dimensions: "Dimensiuni Produs Finit (ex: 25x100x4000mm)",
  lumberGrade: "Clasă Calitate Cherestea/Produs",
  surfaceFinish: "Finisaj Suprafață",
  moistureContent: "Conținut Umiditate (ex: KD 15-19%)",
  treatment: "Tratament Aplicat (ex: Termic, Antifungic)",
  processedWeightKg: "Greutate Produs Finit (kg)",
};

export default labels;