
import { Material, MaterialState, MaterialType, OwnershipStatus, ForestType, SurfaceFinishType } from '../types';

const mockMaterials: Material[] = [
    {
        id: "MAT-002B",
        nume: "Buștean Fag Calitatea A",
        descriere: "Bușteni de fag de calitate superioară, diametru mediu 40cm, pentru cherestea de export.",
        tip: MaterialType.PRIME,
        stare: MaterialState.RECEIVED,
        supplierId: "SUP-001", 
        createdAt: "2025-06-10T10:05:00Z",
        updatedAt: "2025-06-10T10:05:00Z",
        componente: [],
        // Lumber Mill - PRIME
        logDiameter: "35-45 cm",
        logLength: "3m, 4m",
        logGrade: "A/B Mixt",
        estimatedWeightKg: "18000", // For a batch
        defectDescription: "Ușoare curburi, noduri sănătoase < 3cm",
        // IKEA Fields - PRIME
        countryOfHarvest: "România",
        regionAndForestName: "Prahova, Pădurea Măneciu, UP IV",
        gpsCoordinatesOrFMU: "FMU-PH-1023 / 45.345N, 25.876E",
        forestOwnership: OwnershipStatus.PUBLIC,
        forestType: ForestType.SEMI_NATURAL,
        harvestDateOrPeriod: "2025-05-15 - 2025-05-30",
        treeSpeciesScientific: "Fagus sylvatica",
        treeSpeciesCommon: "Fag European",
        estimatedVolumePerSpeciesRWE: "150 m³",
        loggingPermitOrLicense: "APV-PH-678/2025 (valabil 2025-05-01 - 2025-07-31)",
        landTenureAndUseRights: "Concesiune Ocol Silvic Măneciu, Contract 12/2020",
        chainOfCustodyRecords: "Lot FS-001/2025 - Aviz primar 12345, Registru intrări OS",
        transportPermits: "Aviz de însoțire seria XY nr. 54321, 54322",
        dueDiligenceRecordsSubSuppliers: "N/A (Sursă directă din pădure gestionată de furnizor)",
        forestCertificationScheme: "FSC",
        certificationNumber: "FSC-C123456",
        certificationScope: "Management Forestier și Lanț de Custodie pentru Ocol Silvic Măneciu",
        certificationValidityPeriod: "2023-01-01 - 2027-12-31",
        productGroupAndClaimType: "FSC 100%",
        cocCertificateCopies: "Certificat FSC-C123456.pdf (disponibil în dosar)",
        certificationAuditSummaries: "Sumar audit FSC 2023 disponibil la cerere.",
        rawMaterialLedgerInfo: "Intrare în registrul de materii prime OS Măneciu, ID intern RM-OSM-2025-Lot12",
        forestManagementPlanDetails: "Plan Amenajistic Ocol Silvic Măneciu 2020-2030, Parcela 35A",
        batchLevelTrackingInfo: "Marcaj fizic pe buștean: Lot FS-001/25/35A",
        worldForestIDParticipation: "Probele trimise pentru analiza amprentei genetice.",
        forensicTestData: "N/A momentan",
        gpsOrBlockchainTraceabilityTools: "GPS pe camioane transport, în curs de explorare blockchain.",
        inputOutputReconciliation: "N/A pentru bustean brut. Se aplică la prelucrare.",
        carbonFootprintData: "Calcul în curs de realizare pentru operațiuni forestiere.",
        resourceEfficiencyOrWasteData: "N/A"
    },
    {
        id: "MAT-001A",
        nume: "Scandura Brad 25x100x4000mm",
        descriere: "Scandura din lemn de brad, calitate A, rindeluita, uscată KD 12-15%.",
        tip: MaterialType.WORKED,
        stare: MaterialState.IN_PROGRESS,
        createdAt: "2025-06-10T10:00:00Z",
        updatedAt: "2025-06-10T10:00:00Z",
        componente: ["MAT-LMB-003"], // Presupunem că MAT-LMB-003 este Buștean Brad
        // Lumber Mill - WORKED
        dimensions: "25x100x4000mm",
        lumberGrade: "Calitatea A (Export)",
        surfaceFinish: SurfaceFinishType.S4S,
        moistureContent: "KD 12-15%",
        treatment: "Tratament antifungic Sinesto B",
        processedWeightKg: "3500", // For a batch/package
        // IKEA Fields - WORKED
        finalProcessingLocation: "România, Fabrica LemnProd Comănești, Bacău",
        ikeaProductType: "Componentă mobilier (ex: laterală sertar, poliță)",
        ikeaProductNamesOrArticles: "PAX-102.456.78 (laterală), BILLY-203.567.89 (poliță)",
        packingListTraceableToRawMaterial: "Packing List PL-SCB-001 (referință la Lot Buștean BS-005/2025)",
        inputOutputReconciliation: "Lot Buștean BS-005: 1.5 m³ -> Lot Scandură SCB-001: 1 m³ (randament 66%)",
        batchLevelTrackingInfo: "Lot producție SCB-2025-06-A (etichetat pe fiecare pachet)",
        recycledContentPercentage: "0%",
        carbonFootprintData: "Calcul intern preliminar: 0.8 kg CO2e/mp (necertificat)",
        worldForestIDParticipation: "În curs de evaluare",
        rawMaterialLedgerInfo: "Referință la intrarea busteanului MAT-LMB-003. Ledger producție intern.",
        resourceEfficiencyOrWasteData: "Deșeuri rumeguș: 15%, Deșeuri capete: 5%. Total valorificat: 90%."
    },
    {
        id: "MAT-003C",
        nume: "Cherestea Stejar Uscată Brut",
        descriere: "Cherestea de stejar uscată în uscător, tivită, calitate AB, grosime 32mm. Stare brută.",
        tip: MaterialType.PRIME, 
        stare: MaterialState.RECEIVED,
        supplierId: "SUP-002",
        createdAt: "2025-06-10T10:10:00Z",
        updatedAt: "2025-06-10T10:10:00Z",
        componente: [],
        logDiameter: "N/A (cherestea)", 
        logLength: "Variabil (2-4m)", 
        logGrade: "AB (Cherestea)",
        estimatedWeightKg: "2500", 
        defectDescription: "Noduri sănătoase admise, alburn pe o față max 10%",
        countryOfHarvest: "România",
        regionAndForestName: "Cluj, Pădurea Făget, UP II",
        gpsCoordinatesOrFMU: "46.73°N 23.54°E (centrul aproximativ al UP)",
        forestOwnership: OwnershipStatus.PRIVATE,
        forestType: ForestType.NATURAL_PRIMARY,
        harvestDateOrPeriod: "2025-04-01 - 2025-04-20",
        treeSpeciesScientific: "Quercus robur",
        treeSpeciesCommon: "Stejar pedunculat",
        estimatedVolumePerSpeciesRWE: "80 m³ (lot recepționat cherestea, nu RWE bustean)",
        loggingPermitOrLicense: "LP-CJ-112/2025 (pentru bustenii originali)",
        chainOfCustodyRecords: "Lot DLT-ST-002/2025 (de la furnizor)",
        forestCertificationScheme: "PEFC",
        certificationNumber: "PEFC/12-34-56",
        productGroupAndClaimType: "PEFC 100% Certified",
        cocCertificateCopies: "PEFC_DLT_COC.pdf",
        batchLevelTrackingInfo: "Lot CHST-DLT-2025-04-02"
    },
    {
        id: "MAT-004D",
        nume: "Panouri Lemn Masiv Stejar Îmbinat",
        descriere: "Panouri din lemn masiv de stejar îmbinat în dinți, 18mm, finisaj natur.",
        tip: MaterialType.WORKED,
        stare: MaterialState.IN_PROGRESS,
        createdAt: "2025-06-10T10:15:00Z",
        updatedAt: "2025-06-11T09:00:00Z",
        componente: ["MAT-003C"], 
        dimensions: "18x600x2400mm (diverse)",
        lumberGrade: "Mobilier Clasa A",
        surfaceFinish: SurfaceFinishType.SANDED,
        moistureContent: "8-10%",
        treatment: "Niciunul",
        processedWeightKg: "1500",
        finalProcessingLocation: "România, Atelier Tâmplărie ArtWood Gherla, Cluj",
        ikeaProductType: "Blat masă, fronturi mobilier, elemente decorative",
        ikeaProductNamesOrArticles: "INGATORP-302.170.65 (blat), BESTA-002.938.80 (front)",
        batchLevelTrackingInfo: "Lot Panou-ST-2025-06-01",
        inputOutputReconciliation: "Lot Cherestea CHST-DLT-2025-04-02 (2m³) -> Lot Panou-ST-2025-06-01 (1.5m³ panouri)",
        packingListTraceableToRawMaterial: "PL-PNST-001 -> Lot CHST-DLT-2025-04-02",
        recycledContentPercentage: "0%"
    },
    {
        id: "MAT-LMB-001",
        nume: "Buștean Stejar Calitatea Extra (Furnir)",
        descriere: "Bușteni de stejar, calitate superioară, fără noduri, diametru > 50cm, pentru furnir.",
        tip: MaterialType.PRIME,
        stare: MaterialState.RECEIVED,
        supplierId: "SUP-004", 
        createdAt: "2025-07-01T08:00:00Z",
        updatedAt: "2025-07-01T08:00:00Z",
        componente: [],
        logDiameter: "> 50 cm",
        logLength: "Variabil (min 2.5m)",
        logGrade: "Extra (Furnir)",
        estimatedWeightKg: "30000",
        defectDescription: "Fără defecte majore, cilindricitate bună",
        countryOfHarvest: "România",
        regionAndForestName: "Iași, Pădurea Bârnova, UP I, Parcela 10",
        gpsCoordinatesOrFMU: "FMU-IS-PVS-001",
        forestOwnership: OwnershipStatus.PRIVATE,
        forestType: ForestType.NATURAL_PRIMARY,
        harvestDateOrPeriod: "2025-06-15",
        treeSpeciesScientific: "Quercus petraea",
        treeSpeciesCommon: "Stejar Sessile",
        estimatedVolumePerSpeciesRWE: "200 m³",
        loggingPermitOrLicense: "APV-IS-EXTRA-001/2025",
        chainOfCustodyRecords: "Lot PVS-STEX-001/2025, Aviz Exploatare IS-00567",
        forestCertificationScheme: "FSC",
        certificationNumber: "FSC-C000001",
        certificationScope: "FM/COC",
        certificationValidityPeriod: "Până la 2028-12-31",
        productGroupAndClaimType: "FSC 100%",
        cocCertificateCopies: "Referință: PVS_FSC_Cert.pdf (server intern)",
        forestManagementPlanDetails: "Plan Amenajistic Pădurea Verde SA 2021-2031",
        batchLevelTrackingInfo: "Lot PVS-STEX-001",
    },
    {
        id: "MAT-LMB-003",
        nume: "Buștean Brad Cal. B (Construcții)",
        descriere: "Bușteni de brad, pentru cherestea și grinzi, diametru 30-60cm.",
        tip: MaterialType.PRIME,
        stare: MaterialState.RECEIVED,
        supplierId: "SUP-003",
        createdAt: "2025-07-03T11:00:00Z",
        updatedAt: "2025-07-03T11:00:00Z",
        componente: [],
        logDiameter: "30-60 cm",
        logLength: "4m, 5m, 6m",
        logGrade: "B (Construcții)",
        estimatedWeightKg: "45000",
        defectDescription: "Noduri sănătoase, curbură ușoară admisă",
        countryOfHarvest: "România",
        regionAndForestName: "Covasna, Pădurea Brețcu, Ocol Silvic Comunal",
        gpsCoordinatesOrFMU: "45.87°N 26.30°E (aproximativ)",
        forestOwnership: OwnershipStatus.COMMUNAL,
        forestType: ForestType.SEMI_NATURAL,
        harvestDateOrPeriod: "Q2 2025 (Mai-Iunie)",
        treeSpeciesScientific: "Abies alba",
        treeSpeciesCommon: "Brad alb",
        estimatedVolumePerSpeciesRWE: "300 m³ (total partidă)",
        loggingPermitOrLicense: "Permis ForestExplo 2025/B - Partida 12B",
        chainOfCustodyRecords: "Lot FE-BR-002B/2025 (din partida 12B)",
        forestCertificationScheme: "FSC Controlat", 
        certificationNumber: "FSC-CW000002 (pentru ForestExplo ca trader)",
        productGroupAndClaimType: "FSC Controlled Wood",
        forestManagementPlanDetails: "Plan de management pădure comunală Brețcu (extras pentru verificarea DDS)",
        dueDiligenceRecordsSubSuppliers: "Dosar DDS pentru Ocolul Silvic Comunal Brețcu",
        batchLevelTrackingInfo: "Lot FE-BR-002B",
    },
    {
        id: "MAT-LMB-101",
        nume: "Grinzi Stejar Lamelat 100x100mm",
        descriere: "Grinzi din stejar lamelat, calitate A, uscate, pentru structuri și design.",
        tip: MaterialType.WORKED, 
        stare: MaterialState.IN_PROGRESS,
        createdAt: "2025-07-05T14:00:00Z",
        updatedAt: "2025-07-05T14:00:00Z",
        componente: ["MAT-LMB-001"], 
        dimensions: "100x100x3000mm (diverse lungimi)",
        lumberGrade: "Structural Clasa GL24h",
        surfaceFinish: SurfaceFinishType.S4S,
        moistureContent: "10-12%",
        treatment: "Opțional - Ignifugare la cerere",
        processedWeightKg: "12000",
        finalProcessingLocation: "România, Gater Propriu Pădurea Verde SA, Iași",
        ikeaProductType: "Elemente structurale mobilier, grinzi decorative",
        batchLevelTrackingInfo: "Lot GR-ST-2025-07-01",
        inputOutputReconciliation: "Lot Buștean PVS-STEX-001 (parte din el) -> Lot Grinzi GR-ST-2025-07-01",
        ikeaProductNamesOrArticles: "IVAR-Series Components, Custom Projects",
        packingListTraceableToRawMaterial: "PL-GRST-001 -> Lot PVS-STEX-001",
        recycledContentPercentage: "0%",
    },
];

export default mockMaterials;
