
import { Supplier } from '../types';

const mockSuppliers: Supplier[] = [
  {
    id: "SUP-001",
    nume: "Ocolul Silvic Măneciu SRL",
    persoanaContact: "Ion Popescu",
    email: "ion.popescu@maneciu.ro",
    telefon: "0722000111",
    adresa: "Str. Principală 1, Măneciu, Prahova",
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-10T10:00:00Z",
    // IKEA Fields
    ikeaSupplierId: "IKEA-OSM-123",
    complianceOfficerInfo: "Ana Vasilescu - ana.vasilescu@maneciu.ro / 0722111222",
    subSupplierInfo: "Nu se aplică (majoritatea din surse proprii gestionate)",
    traceabilitySystemDescription: "Sistem manual bazat pe avize de însoțire și registru intrări-ieșiri. Marcaje fizice pe loturi.",
    supplyChainFlowChartData: "Document intern: 'Flux Aprovizionare OS Maneciu V2.pdf'",
    latestThirdPartyAuditReports: "Audit FSC 2023 - Certificat valid (FSC-C123456). Raport disponibil la cerere.",
    correctiveActionPlans: "CAP 2023.01 (Observație minoră trasabilitate internă) - Închis la 15.03.2023.",
    ikeaOwnAuditResults: "Audit IWAY Q2 2023 - Conformitate generală bună. Plan de îmbunătățire pentru digitalizare trasabilitate.",
    legalComplianceDeclarations: "Declarație EUTR pentru toate exporturile către UE. Document Due Diligence actualizat Q1 2024.",
  },
  {
    id: "SUP-002",
    nume: "Depozit Lemn Transilvania SA",
    persoanaContact: "Vasile Gheorghe",
    email: "contact@depozitlemn-transilvania.com",
    telefon: "0733000222",
    adresa: "Str. Depozitului 5, Cluj-Napoca, Cluj",
    createdAt: "2024-01-15T11:30:00Z",
    updatedAt: "2024-02-01T09:15:00Z",
    ikeaSupplierId: "IKEA-DLT-456",
    complianceOfficerInfo: "Mihai Sandu - mihai.sandu@depozitlemn.com / Conformitate: Adina Barbu - adina.barbu@depozitlemn.com",
    subSupplierInfo: "Parteneriate cu 3 gatere locale: Gaterul Mic SRL (ID: SUB-GMS), LemnProces Prod (ID: SUB-LPP), Taietura Dreapta SRL (ID: SUB-TDS). Documentație DDS per sub-furnizor disponibilă.",
    traceabilitySystemDescription: "Software custom 'WoodTrack v2.1', integrat cu coduri de bare per lot. Reconciliere lunară.",
    supplyChainFlowChartData: "Vezi anexa 'SupplyChain_DLT_2024.pdf'",
    latestThirdPartyAuditReports: "Audit PEFC 2023 - Recertificare în progres. Ultimul certificat PEFC/07-31-100 valid până la 31.12.2023. Audit IKEA planificat Q3 2024.",
    correctiveActionPlans: "Nu sunt planuri active. Urmărire recomandări audit intern.",
    ikeaOwnAuditResults: "N/A - Primul audit IKEA programat Q4 2024",
    legalComplianceDeclarations: "Declarație pe proprie răspundere privind legalitatea lemnului conform normelor UE și naționale. Registru DDS menținut.",
  },
  {
    id: "SUP-003",
    nume: "Forest Explo SRL",
    persoanaContact: "Maria Ionescu",
    email: "maria.ionescu@forestexplo.ro",
    telefon: "0744000333",
    adresa: "Calea Moșilor 100, București",
    createdAt: "2024-02-01T08:00:00Z",
    updatedAt: "2024-02-01T08:00:00Z",
    ikeaSupplierId: "IKEA-FEX-789",
    complianceOfficerInfo: "George Enescu - george.enescu@forestexplo.ro",
    subSupplierInfo: "Achiziții directe de la proprietari de păduri mici (peste 200 contracte active). Se menține listă cu DDS.",
    traceabilitySystemDescription: "Sistem hibrid: documente fizice (avize, contracte) și registru Excel centralizat pentru loturi.",
    supplyChainFlowChartData: "Flux simplu: Pădure (multipli proprietari mici) -> Depozit Forest Explo -> Client. Diagrama disponibilă.",
    latestThirdPartyAuditReports: "Certificat de Origine Controlată (COC) - 2024-COC-00123. Nu deține certificare FSC/PEFC pentru păduri.",
    correctiveActionPlans: "N/A",
    ikeaOwnAuditResults: "Audit preliminar IKEA Q1 2024 - Necesită îmbunătățirea sistemului DDS pentru sub-furnizori multipli.",
    legalComplianceDeclarations: "Documente standard de proveniență. Se lucrează la implementarea unui sistem DDS mai robust.",
  },
  {
    id: "SUP-004",
    nume: "Pădurea Verde SA",
    persoanaContact: "Andrei Stamate",
    email: "andrei@padurea-verde.ro",
    telefon: "0755000444",
    adresa: "Bvd. Independenței 22, Iași",
    createdAt: "2024-02-10T14:20:00Z",
    updatedAt: "2024-02-10T14:20:00Z",
    ikeaSupplierId: "IKEA-PVS-101",
    complianceOfficerInfo: "Laura Popa - laura.popa@padurea-verde.ro / Director Calitate: Radu Dumitru",
    subSupplierInfo: "Exclusiv din păduri proprii certificate FSC.",
    traceabilitySystemDescription: "Sistem integrat GIS pentru management forestier și trasabilitate loturi de la arbore la poarta fabricii. Software SAP pentru gestiune.",
    supplyChainFlowChartData: "GIS-Pădure -> Transport Intern -> Gater Propriu -> Depozit Produse Finite -> Client. Flux documentat și auditat.",
    latestThirdPartyAuditReports: "Audit FSC FM/COC - Certificat Gold Standard (FSC-C000001). Raport anual de supraveghere disponibil.",
    correctiveActionPlans: "Minor non-conformity Q1 2023 (etichetare internă) - Remediat și verificat în auditul de supraveghere.",
    ikeaOwnAuditResults: "Excelent - Audit IWAY Q1 2024. Puncte forte: trasabilitate și management forestier.",
    legalComplianceDeclarations: "Toate declarațiile la zi, inclusiv EUTR, UKTR. Membru WWF GFTN.",
  },
  {
    id: "SUP-005",
    nume: "Silvicom SRL",
    persoanaContact: "Elena Dobre",
    email: "elena.dobre@silvicom.ro",
    telefon: "0766000555",
    adresa: "Str. Forestieră 12, Suceava",
    createdAt: "2024-03-05T16:00:00Z",
    updatedAt: "2024-03-05T16:00:00Z",
    ikeaSupplierId: "IKEA-SLV-112",
    complianceOfficerInfo: "Cristian Munteanu - cristian.munteanu@silvicom.ro",
    subSupplierInfo: "Colaborare cu Asociația Proprietarilor de Păduri Bucovina (ID SUB-APPB) - lemn certificat FSC group scheme.",
    traceabilitySystemDescription: "Sistem de management al documentelor și etichetare fizică. Se implementează un sistem digital.",
    supplyChainFlowChartData: "Vezi 'Procedura Trasabilitate Silvicom V1.2.pdf'",
    latestThirdPartyAuditReports: "Control de legalitate DDS - Conform (Raport Control SILV SV 2023/58). Certificare FSC CoC (FSC-C987654).",
    correctiveActionPlans: "Plan pentru digitalizarea completă a trasabilității până în Q4 2024.",
    ikeaOwnAuditResults: "Audit IWAY Q2 2024 - Recomandări pentru digitalizare și îmbunătățirea reconcilierii volumelor.",
    legalComplianceDeclarations: "Declarație UKTR pentru exporturi în UK. Documentație DDS la zi.",
  }
];

export default mockSuppliers;
